# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/shreya/frontend_for_me/SoC_PJT/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_interconnect_0_upgraded_ipi_imp_xbar_0/design_1_axi_interconnect_0_upgraded_ipi_imp_xbar_0.xci
# IP: The module: 'design_1_axi_interconnect_0_upgraded_ipi_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/shreya/frontend_for_me/SoC_PJT/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_interconnect_0_upgraded_ipi_imp_xbar_0/design_1_axi_interconnect_0_upgraded_ipi_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_interconnect_0_upgraded_ipi_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/shreya/frontend_for_me/SoC_PJT/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_axi_interconnect_0_upgraded_ipi_imp_xbar_0/design_1_axi_interconnect_0_upgraded_ipi_imp_xbar_0.xci
# IP: The module: 'design_1_axi_interconnect_0_upgraded_ipi_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/shreya/frontend_for_me/SoC_PJT/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_axi_interconnect_0_upgraded_ipi_imp_xbar_0/design_1_axi_interconnect_0_upgraded_ipi_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_interconnect_0_upgraded_ipi_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
