# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/shreya/frontend_for_me/SoC_PJT/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_picorv32_core_0_0/design_1_picorv32_core_0_0.xci
# IP: The module: 'design_1_picorv32_core_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/shreya/frontend_for_me/SoC_PJT/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_picorv32_core_0_0/src/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: /home/shreya/frontend_for_me/SoC_PJT/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_picorv32_core_0_0/src/blk_mem_gen_0_ooc.xdc

# IP: /home/shreya/frontend_for_me/SoC_PJT/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_picorv32_core_0_0/design_1_picorv32_core_0_0.xci
# IP: The module: 'design_1_picorv32_core_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/shreya/frontend_for_me/SoC_PJT/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_picorv32_core_0_0/src/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: /home/shreya/frontend_for_me/SoC_PJT/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_picorv32_core_0_0/src/blk_mem_gen_0_ooc.xdc
